### PR TITLE
Don't use private class LinkReferenceProvider

### PR DESCRIPTION
**Pull request by kyteinsky**
Solves #1

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Ah wait, the embed only works for web. The open graph fallback was still useful for mobile apps like talk

**Comment by kyteinsky** [comment]
Aaah, I'll add it back in this PR itself.

**Comment by kyteinsky** [comment]
Do we bump php version as well?

**Review by marcelklehr — APPROVED** [review]
:elephant:

**Pull request merged**
